### ISSUE TITLE
I run into an error on each synch "return mailcow_response["active"] != active or \ TypeError: list indices must be integers or slices, not str"

### ISSUE THREAD

**Issue by theoneandonly-vector** [myOmikron/mailcow-ldap-sync#11]
```
None
Traceback (most recent call last):
  File "./main.py", line 332, in <module>
    main(config, session, change_only_by_ldap=args.change)
  File "./main.py", line 149, in main
    if not change_only_by_ldap or is_diff(
  File "./main.py", line 16, in is_diff
    return mailcow_response["active"] != active or \
TypeError: list indices must be integers or slices, not str
```

**Comment by theoneandonly-vector** [comment]
this only happens when I use "--update-only-on-change-by-ldap"
I have two setups and it only happens on one of them

**Comment by myOmikron** [comment]
Does this problem still occur?
