### ISSUE TITLE
new issue, most likely related to my LDAP source

### ISSUE THREAD

**Issue by theoneandonly-vector** [myOmikron/mailcow-ldap-sync#18]
I didntt change anythign on my config but now get the following error:

```
Traceback (most recent call last):
  File "./main.py", line 332, in <module>
    main(config, session, change_only_by_ldap=args.change)
  File "./main.py", line 47, in main
    password = user_params[conf['ldap']['user_mapping']['password']][0].decode('utf-8')
KeyError: 'userPassword'
```

maybe someone can help me how to debug this?

**Comment by theoneandonly-vector** [comment]
my synch-user lost admin, idk why..
